before_install:
  - gem install cocoapods
  - brew update && brew upgrade swiftlint
  - gem update concurrent-ruby
  - pod setup
install:
  - pod repo update
  - pod install --project-directory=SpaceLaunches/ --repo-update
language: swift
osx_image: xcode12.2
xcode_workspace: SpaceLaunches/SpaceLaunches.xcworkspace
xcode_scheme: SpaceLaunches
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12
script:
 - xcodebuild test -workspace 'SpaceLaunches/SpaceLaunches.xcworkspace' -scheme 'SpaceLaunches' -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 12' -quiet
