# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/mryusuf/space-launches-corepodspec'

use_frameworks!

workspace 'SpaceLaunches'

def core_pods
  pod 'RxSwift', '~>5.0'
  pod 'RealmSwift', '~> 10'
end

def feature_pods
  pod 'Alamofire', '~> 5.2'
  pod 'RxDataSources', '~> 4.0'
  pod 'Core', '1.0.1'
end

target 'SpaceLaunches' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  # Pods for SpaceLaunches
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'RxCocoa', '~>5.0'
  pod 'RxDataSources', '~> 4.0'
  pod "SnapKit", "~> 5.0.0"
  pod 'Lightbox'
  pod 'Core', '1.0.1'
  core_pods
end


target 'Home' do
  project '../Home/Home'
  feature_pods
end

target 'HomeTests' do
  project '../Home/Home'
  feature_pods
  pod 'RxBlocking'
end

target 'LaunchDetail' do
  project '../LaunchDetail/LaunchDetail'
  feature_pods
end

target 'LaunchDetailTests' do
  project '../LaunchDetail/LaunchDetail'
  feature_pods
  pod 'RxBlocking'
end

target 'Watchlist' do
  project '../Watchlist/Watchlist'
  feature_pods
end

target 'WatchlistTests' do
  project '../Watchlist/Watchlist'
  feature_pods
  pod 'RxBlocking'
end

target 'About' do
  project '../About/About'
  pod 'RxSwift', '~>5.0'
  pod 'Core', '1.0.1'
end

